### ISSUE TITLE
5.0 Epic

### ISSUE THREAD

**Issue by JerryBian** [JerryBian/swan#173]
- [x] add Admin/Api sites as microservice.
- [x] publish docker images
- [x] support Local/GitHub source
- [x] authentication
- [x] healthcheck for API
- [x] GitHub hook event
- [x] Post access
- [x] GitHub save back
