### ISSUE TITLE
5.5 Epic

### ISSUE THREAD

**Issue by JerryBian** [JerryBian/swan#178]
**Refactor** 

- [ ] Remove all comments stuffs
- [ ] Reduce hardcoded strings
- [ ] Use Polly in more places
- [ ] Beautify Startup.cs
- [ ] Resort Share project - only those are referenced by multiple projects put here
- [ ] Add more email notify

**Comment by JerryBian** [comment]
**Verify**

- [x] SEO & HTML/CSS/RSS standard
- [ ] Add/Update new post during runtime: visible if published, visible after sometime, all pages cache refreshed
- [x] Visit post, access increase
- [x] About page for Desktop and Mobile
- [x] Icons
- [x] Minimize Configurations
- [x] Push to DB automatically(with correct commit messages)
- [ ] Thread safety
- [x] All images shown correctly
- [ ] For certain cases - push before pull
- [x] Include Katex for certain posts
- [ ] All admin posts should work properly
