### ISSUE TITLE
5.6 Epic

### ISSUE THREAD

**Issue by JerryBian** [JerryBian/swan#179]
- [x] API call attach and verify Token
- [ ] Readme 
- [x] Email notify
- [x] Logging
- [ ] CSS minify
- [ ] External link attach Icon
- [ ] Post images pop up
- [ ] Post outline in aside
