### ISSUE TITLE
6.0 Epic

### ISSUE THREAD

**Issue by JerryBian** [JerryBian/swan#180]
- [x] Upgrade to .NET 6
- [x] Upgrade all libraries to latest
- [x] Use latest Microsoft images
- [x] use latest C# features
- [x] Dynamic PGO
- [x] EnableSingleFileAnysis On

**Comment by JerryBian** [comment]
God... `DateOnly` cannot work with ASP.NET Model Binding at all.... Why Microsoft create a new thing but didn't make it work!

https://github.com/dotnet/runtime/issues/53539

Will continue to use `DateTime` now.
